/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventario;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dannia
 */
public class Sistema extends javax.swing.JFrame {

    DefaultTableModel model;

    public DefaultTableModel getModel() {
        return model;
    }

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/inventario.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_Nuevo = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInventario = new javax.swing.JTable();
        jTextBusqueda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario");
        setBackground(new java.awt.Color(104, 116, 242));
        setIconImage(getIconImage());
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Inventario");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_Nuevo.setText("Nuevo");
        btn_Nuevo.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevoActionPerformed(evt);
            }
        });

        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btn_Editar.setText("Editar");
        btn_Editar.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        jTableInventario = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        };
        jTableInventario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Num. Articulo", "Nombre", "Descripcion", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableInventario.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableInventario.setEditingColumn(0);
        jTableInventario.setEditingRow(0);
        jTableInventario.setFocusable(false);
        jTableInventario.setRowHeight(30);
        jTableInventario.getTableHeader().setResizingAllowed(false);
        jTableInventario.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableInventario);
        if (jTableInventario.getColumnModel().getColumnCount() > 0) {
            jTableInventario.getColumnModel().getColumn(0).setResizable(false);
            jTableInventario.getColumnModel().getColumn(0).setPreferredWidth(59);
            jTableInventario.getColumnModel().getColumn(1).setResizable(false);
            jTableInventario.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableInventario.getColumnModel().getColumn(2).setResizable(false);
            jTableInventario.getColumnModel().getColumn(2).setPreferredWidth(300);
            jTableInventario.getColumnModel().getColumn(3).setResizable(false);
            jTableInventario.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTableInventario.getColumnModel().getColumn(4).setResizable(false);
            jTableInventario.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        jTextBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextBusquedaKeyTyped(evt);
            }
        });

        jLabel2.setText("Busqueda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(31, 31, 31))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(389, 389, 389)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBusquedaKeyReleased
        Conexion con = new Conexion();
        //Actualiza la tabla buscando los datos ingresados en la caja de texto
        this.actualizarTabla(con.busqueda(jTextBusqueda.getText()));
    }//GEN-LAST:event_jTextBusquedaKeyReleased

    private void btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoActionPerformed
        // TODO add your handling code here:
        AgregarArticulo nuevoArticulo = new AgregarArticulo();
        //Declaramos el estado que posteriormente servira para mostrar en la ventana AgregarArticulo el boton guardar
        nuevoArticulo.setEstado(0);
        nuevoArticulo.revisarEstado();
        nuevoArticulo.setTitle("Agregar articulo");
        nuevoArticulo.show();
        this.dispose();
    }//GEN-LAST:event_btn_NuevoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        actualizarTabla(new Conexion().llenarTabla());
    }//GEN-LAST:event_formWindowOpened

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        // TODO add your handling code here:
        int index = jTableInventario.getSelectedRow();
        
        //Validamos que se haya seleccionado algun renglon y confirmamos la eliminacion
        if (index != -1 && JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar este articulo? ", "ATENCION", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0) {
            int id = Integer.parseInt(jTableInventario.getValueAt(index, 0).toString());
            Conexion con = new Conexion();
            con.eliminarArticulo(id);
            actualizarTabla(con.llenarTabla());
        } else if (index == -1) {
            JOptionPane.showMessageDialog(null, "Selecciona un articulo", "Ha ocurrido un error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        // TODO add your handling code here:
        int index = jTableInventario.getSelectedRow();
        
        
        if(index != -1){
          AgregarArticulo nuevoArticulo = new AgregarArticulo();
          //Declaramos el estado que posteriormente servira para mostrar en la ventana AgregarArticulo el boton actualizar
          nuevoArticulo.setEstado(1);
          //Cargamos los datos seleccionados de la tabla de articulos
          nuevoArticulo.setId(jTableInventario.getValueAt(index, 0).toString());
          nuevoArticulo.setNombre(jTableInventario.getValueAt(index, 1).toString());
          nuevoArticulo.setDescripcion(jTableInventario.getValueAt(index, 2).toString());
          nuevoArticulo.setCantidad(jTableInventario.getValueAt(index, 3).toString());
          nuevoArticulo.setPrecio(jTableInventario.getValueAt(index, 4).toString());
          nuevoArticulo.cargarDatos();
          nuevoArticulo.revisarEstado();
          nuevoArticulo.setTitle("Modificar articulo");
          nuevoArticulo.show();
          this.dispose();
        }else{
           JOptionPane.showMessageDialog(null, "Selecciona un articulo", "Ha ocurrido un error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_EditarActionPerformed

    private void jTextBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBusquedaKeyTyped
        // Convierte las letras a mayusculas
        char caracter = evt.getKeyChar();
        if (Character.isLowerCase(caracter) == true) {
            evt.setKeyChar(Character.toUpperCase(caracter));
        }
        // Permite solo letras en la caja de texto de busqueda
        if(!Character.isLetter(caracter)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextBusquedaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
             UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");    

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    public void actualizarTabla(DefaultTableModel model) {
        //Construimos el modelo y las dimensiones de cada columna
       jTableInventario.setModel(model);
       jTableInventario.getColumnModel().getColumn(0).setPreferredWidth(59);
       jTableInventario.getColumnModel().getColumn(1).setPreferredWidth(150);
       jTableInventario.getColumnModel().getColumn(2).setPreferredWidth(300);
       jTableInventario.getColumnModel().getColumn(3).setPreferredWidth(80);
       jTableInventario.getColumnModel().getColumn(4).setPreferredWidth(80);

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableInventario;
    private javax.swing.JTextField jTextBusqueda;
    // End of variables declaration//GEN-END:variables
}
